name: Prepare release asset
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: true
    default: ${{ github.token }}
  component:
    description: 'Integration Component being release'
    required: true
runs:
  using: composite
  steps:
    - name: Update requirements.txt
      shell: bash
      run: python3 ${{ github.action_path }}/helpers/update_requirements.py --component ${{ inputs.COMPONENT }}
    - name: check for changes
      shell: bash
      run: git status
    - name: stage changed files
      shell: bash
      run: git add requirements.txt
    - name: commit changed files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "dep: Auto update requirements.txt" || true
    - name: Update manifest.json
      shell: bash
      run: python3 ${{ github.action_path }}/helpers/update_version.py --tag ${{ github.ref }} --component ${{ inputs.COMPONENT }}
    - name: check for changes
      shell: bash
      run: git status
    - name: stage changed files
      shell: bash
      run: git add ./custom_components/${{ inputs.COMPONENT }}/manifest.json
    - name: commit changed files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "rel: Auto update manifest.json" || true
        git tag -fa ${{ github.event.release.tag_name }} -m "Update version number ${{ github.event.release.tag_name }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
    - name: Push tag change
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        force: true
        tags: true
    # Pack the Component dir as a zip and upload to the release
    - name: ZIP Component Dir
      shell: bash
      run: |
        cd ${{ github.workspace }}/custom_components/${{ inputs.COMPONENT }}
        zip ${{ inputs.COMPONENT }}.zip -r ./
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/custom_components/${{ inputs.COMPONENT }}/${{ inputs.COMPONENT }}.zip
        asset_name: ${{ inputs.COMPONENT }}.zip
        tag: ${{ github.ref }}
        overwrite: true
