name: Prepare release notes
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: true
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Enable version 3.11 of Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12

    - name: Install requirements
      shell: bash
      run: |
        python3 -m pip install setuptools wheel
        python3 -m pip install -r ${{ github.workspace }}/requirements_release.txt

    - name: Update release notes and changelog
      shell: bash
      run: python3 ${{ github.action_path }}/helpers/generate_releasenotes.py --token ${{ inputs.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }} --repository ${{ github.repository }} --creator ${{ github.actor }}

    - name: Pull any other changes
      shell: bash
      run: git pull
    - name: Check for changes
      shell: bash
      run: git status
    - name: Stage changed files
      shell: bash
      run: git add ./CHANGELOG.md
    - name: Commit changed files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "doc: Update changelog with release notes" || true
        git tag -fa ${{ github.event.release.tag_name }} -m "Update changelog with release notes ${{ github.event.release.tag_name }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
    - name: Push tag change
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        force: true
        tags: true